version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: mlops-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
