# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\tmlservice\"\x19\n\x17ListModelClassesRequest\";\n\x0eModelClassInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x13\x64\x65\x66\x61ult_params_json\x18\x02 \x01(\t\"F\n\x18ListModelClassesResponse\x12*\n\x07\x63lasses\x18\x01 \x03(\x0b\x32\x19.mlservice.ModelClassInfo\"X\n\x11TrainModelRequest\x12\x14\n\x0c\x64\x61taset_name\x18\x01 \x01(\t\x12\x13\n\x0bmodel_class\x18\x02 \x01(\t\x12\x18\n\x10hyperparams_json\x18\x03 \x01(\t\";\n\x12TrainModelResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x13\n\x0bmodel_class\x18\x02 \x01(\t\"D\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x01\x12\x12\n\nn_features\x18\x03 \x01(\x05\"&\n\x0fPredictResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x01\x32\xf5\x01\n\tMLService\x12[\n\x10ListModelClasses\x12\".mlservice.ListModelClassesRequest\x1a#.mlservice.ListModelClassesResponse\x12I\n\nTrainModel\x12\x1c.mlservice.TrainModelRequest\x1a\x1d.mlservice.TrainModelResponse\x12@\n\x07Predict\x12\x19.mlservice.PredictRequest\x1a\x1a.mlservice.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTMODELCLASSESREQUEST']._serialized_start=31
  _globals['_LISTMODELCLASSESREQUEST']._serialized_end=56
  _globals['_MODELCLASSINFO']._serialized_start=58
  _globals['_MODELCLASSINFO']._serialized_end=117
  _globals['_LISTMODELCLASSESRESPONSE']._serialized_start=119
  _globals['_LISTMODELCLASSESRESPONSE']._serialized_end=189
  _globals['_TRAINMODELREQUEST']._serialized_start=191
  _globals['_TRAINMODELREQUEST']._serialized_end=279
  _globals['_TRAINMODELRESPONSE']._serialized_start=281
  _globals['_TRAINMODELRESPONSE']._serialized_end=340
  _globals['_PREDICTREQUEST']._serialized_start=342
  _globals['_PREDICTREQUEST']._serialized_end=410
  _globals['_PREDICTRESPONSE']._serialized_start=412
  _globals['_PREDICTRESPONSE']._serialized_end=450
  _globals['_MLSERVICE']._serialized_start=453
  _globals['_MLSERVICE']._serialized_end=698
# @@protoc_insertion_point(module_scope)
